### ISSUE TITLE
Improvements suggestion

### ISSUE THREAD

**Issue by gumosun** [dennisluo1/GlobalEducationalExchange#1]
Ways to improve web platform: 
*Combine register/login/my profile
*About page (how to fund raise money)
*Work on more CSS particularly for donation page
*Need to develop payment system
*Change the Country Info Page (it may not be necessary for what I want to build)
*Develop fund-raising page, actually takes in money
*Develop a more structure system (teachers in public teachers)

**Comment by dennisluo1** [comment]
Thanks for the feedback! I definitely want to combine the register/login/my profile pages into just a bar of its own at the top right. Maybe at one point I want to combine the nav bar into just one button that drops down. It would be great to develop the donation page for the platform so that users can fund-raise for their projects and donors can donate to support causes. Also, the CSS is going to be work-in-progress for the entire process. I have a lot to work on!
